### ISSUE TITLE
! Undefined control sequence. ?

### ISSUE THREAD

**Issue by gliptak** [BetterCrypto/Applied-Crypto-Hardening#382]
The following line https://github.com/BetterCrypto/Applied-Crypto-Hardening/blob/master/src/common/commands.tex#L41 shows

```
(/root/.miktex/texmfs/install/tex/latex/seqsplit/seqsplit.sty)
(common/cipherStringB.tex)) (common/configfiles.tex) (common/names.tex
! Undefined control sequence.
\\doindex [#1]#2->\newterm 
                           [name={#2},#1]{index-#2}
l.7 \doindex{Linux}
                   
? 
```

Would you have some pointers how to correct?

**Comment by gliptak** [comment]
@aaronkaplan @azet please comment

**Comment by aaronkaplan** [comment]
Dear @gliptak ,

please note that we are expiring the LaTeX code of the document. We moved to asciidoc since it is way way easier to edit (you can edit it directly on github) and make pull requests. It also does not throw these hard to understand LaTeX compile errors.

Can you please have a look at the new asciidoc branch?
